apiVersion: v1
kind: Namespace
metadata:
  name: harbor-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-config
  namespace: harbor-ns
data:
  app.conf: |
    [core]
    hostname = harbor.civil3.xyz
    httpport = 80
    secret = 123654
  key: |
    123654
  harbor.yml: |
    hostname: harbor.civil3.xyz
    http:
      port: 8080
    data_volume: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc
  namespace: harbor-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-deployment
  namespace: harbor-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-app
  template:
    metadata:
      labels:
        app: harbor-app
    spec:
      containers:
        - name: harbor
          image: bitnami/harbor-core:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: harbor-storage
              mountPath: /data
            - name: harbor-config
              mountPath: /etc/core
              # readOnly: false
              # subPath: app.conf
          # env:
          #   - name: CORE_KEY
          #     value: "123654"  # 设置你的密钥
      volumes:
        - name: harbor-storage
          persistentVolumeClaim:
            claimName: harbor-pvc
        - name: harbor-config
          configMap:
            name: harbor-config
---
apiVersion: v1
kind: Service
metadata:
  name: harbor-service
  namespace: harbor-ns
spec:
  selector:
    app: harbor-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harbor-ingress
  namespace: harbor-ns
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # traefik.ingress.kubernetes.io/router.middlewares: default/strip-prefix
spec:
  rules:
  - host: harbor.civil3.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harbor-service
            port:
              number: 80
