apiVersion: v1
kind: Namespace
metadata:
  name: searxng-ns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-pvc
  namespace: searxng-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng-deployment
  namespace: searxng-ns
  # labels:
  #   app: nginx-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng-app
  template:
    metadata:
      labels:
        app: searxng-app
    spec:
      containers:
        - name: searxng
          image: searxng/searxng
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: searxng-vol
              mountPath: /etc/searxng
      volumes:
        - name: searxng-vol
          persistentVolumeClaim:
            claimName: searxng-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: searxng-svc
  namespace: searxng-ns
spec:
  selector:
    app: searxng-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: searxng-igs
  namespace: searxng-ns
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # traefik.ingress.kubernetes.io/router.middlewares: default/strip-prefix
spec:
  rules:
  - host: searxng.civil3.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: searxng-svc
            port:
              number: 80
